[package]
name = "datawire-client"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.35.0"
egui_plot = "0.36.0"
ehttp = "0.5"
serde = "1"
serde_json = "1"
datawire-shared = { path = "../shared" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.76"
web-sys = { version = "0.3.103", features = ["Window", "Document", "HtmlCanvasElement"] }
